### ISSUE TITLE
New release assets blank

### ISSUE THREAD

**Issue by RobertLowe** [heroku/heroku-nodejs-plugin#41]
@danielleadams

All v8 files are 38 bytes

https://github.com/heroku/heroku-nodejs-plugin/releases 

Our pipeline broke because of this

**Comment by danielleadams** [comment]
@RobertLowe Thanks for the heads up. We moved the plugin to a new pipeline, but it looks like something eventually went wrong with the release. I will remove the release so that v7 is the latest.

One question - how are you using the addon separately from the buildpack? The [Heroku buildpack](https://github.com/heroku/heroku-buildpack-nodejs) will always have the latest stable version of the addon, but understand if you're not using the buildpack.

**Comment by danielleadams** [comment]
Closed since the release has been removed.
